"""
Monthly Synthesis Module

Aggregates weekly assessment outputs across all projects and generates:
1. A cross-project synthesis narrative
2. A 5-7 slide executive PowerPoint presentation
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional

import config
from reasoning_agent import generate_cross_project_synthesis
from presentation_builder import build_monthly_presentation


def load_assessments_from_json(directory: Optional[Path] = None) -> List[Dict]:
    """
    Load all assessment JSON files from the weekly reports directory.
    """
    if directory is None:
        directory = config.WEEKLY_DIR
    
    assessments = []
    json_files = sorted(directory.glob("*_assessment.json"))
    
    if not json_files:
        print(f"⚠️  No assessment JSON files found in: {directory}")
        return assessments
    
    for filepath in json_files:
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                assessment = json.load(f)
                assessments.append(assessment)
                print(f"  📄 Loaded: {filepath.name}")
        except Exception as e:
            print(f"  ❌ Error loading {filepath.name}: {e}")
    
    return assessments


def generate_monthly_report(assessments: Optional[List[Dict]] = None) -> str:
    """
    Generate the complete monthly synthesis:
    1. Load assessments (if not provided)
    2. Generate cross-project narrative
    3. Build PowerPoint presentation
    4. Save everything
    """
    print("\n📊 Monthly Synthesis")
    print("=" * 60)
    
    # Load assessments if not provided
    if assessments is None:
        print("\n📂 Loading weekly assessments...")
        assessments = load_assessments_from_json()
    
    if not assessments:
        print("❌ No assessments available. Run weekly reports first.")
        return ""
    
    print(f"\n✅ {len(assessments)} project assessment(s) loaded")
    
    # Generate synthesis narrative
    print("\n📝 Generating cross-project synthesis...")
    synthesis = generate_cross_project_synthesis(assessments)
    
    # Save synthesis as Markdown
    synthesis_path = config.MONTHLY_DIR / f"Monthly_Synthesis_{datetime.now().strftime('%Y_%m')}.md"
    
    synthesis_report = f"""# Monthly Project Health Synthesis

**Report Period:** {datetime.now().strftime('%B %Y')}  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  
**Projects Analyzed:** {len(assessments)}

---

## Portfolio Summary

| Project | RAG | Score | Confidence |
|---------|-----|-------|------------|
"""
    for a in assessments:
        rag = a.get("overall_rag", "Unknown")
        emoji = config.RAG_EMOJIS.get(rag, "⚪")
        synthesis_report += f"| {a.get('project_name', 'Unknown')} | {emoji} {rag} | {a.get('composite_score', 'N/A')}/3.00 | {a.get('confidence', 'N/A')} |\n"
    
    synthesis_report += f"""
---

{synthesis}

---

*Generated by Project Health Reporting Agent v1.0*
"""
    
    synthesis_path.write_text(synthesis_report, encoding="utf-8")
    print(f"  ✅ Synthesis saved: {synthesis_path}")
    
    # Build PowerPoint
    print("\n📊 Building executive presentation...")
    pptx_path = build_monthly_presentation(assessments, synthesis)
    print(f"  ✅ Presentation saved: {pptx_path}")
    
    return pptx_path


if __name__ == "__main__":
    generate_monthly_report()
