"""
Weekly Report Generator

Produces formatted Markdown reports for each project with:
- Overall RAG status
- Dimension breakdown
- Plain-English reasoning
- Data quality notes
- Key risks and recommendations
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional

import config
from rag_engine import assess_project
from reasoning_agent import generate_reasoning


def _format_dimension_table(dimensions: List[Dict]) -> str:
    """Format dimension scores as a Markdown table."""
    lines = [
        "| Dimension | Weight | Status | Score |",
        "|-----------|--------|--------|-------|",
    ]
    for d in dimensions:
        emoji = config.RAG_EMOJIS.get(d.get("label", "Unknown"), "⚪")
        weight = f"{d['weight']*100:.0f}%"
        label = d.get("label", "Unknown")
        score = f"{d.get('score', '-')}/3" if d.get("score") else "N/A"
        lines.append(f"| {d['dimension']} | {weight} | {emoji} {label} | {score} |")
    return "\n".join(lines)


def _format_metrics_section(dimensions: List[Dict]) -> str:
    """Format key metrics from each dimension."""
    parts = []
    for d in dimensions:
        metrics = d.get("metrics", {})
        if not metrics or not metrics.get("data_available", True):
            continue
        
        parts.append(f"\n### {d['dimension']} — Key Metrics")
        
        # Select interesting metrics (exclude internal flags)
        for k, v in metrics.items():
            if k in ("data_available", "comment_excerpts"):
                continue
            if isinstance(v, list):
                if v:
                    parts.append(f"- **{k.replace('_', ' ').title()}**: {', '.join(str(x) for x in v[:5])}")
            else:
                parts.append(f"- **{k.replace('_', ' ').title()}**: {v}")
    
    return "\n".join(parts)


def generate_weekly_report(project: Dict) -> tuple[str, dict[str, Any]]:
    """
    Generate a complete weekly health report for a single project.
    
    Returns the report as a Markdown string and the assessment dictionary.
    """
    # Run assessment
    assessment = assess_project(project)
    
    # Generate reasoning
    reasoning = generate_reasoning(assessment)
    
    # Build report
    emoji = config.RAG_EMOJIS.get(assessment["overall_rag"], "⚪")
    snapshot = assessment.get("summary_snapshot", {})
    
    report = f"""# Weekly Project Health Report

**Report Date:** {assessment['assessment_date']}  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## Project Overview

| Field | Value |
|-------|-------|
| **Project** | {assessment['project_name']} |
| **Project Manager** | {snapshot.get('project_manager', 'N/A')} |
| **Current Stage** | {snapshot.get('project_stage', 'N/A')} |
| **Timeline** | {snapshot.get('project_start', 'N/A')} → {snapshot.get('project_end', 'N/A')} |
| **% Complete** | {snapshot.get('percent_complete', 'N/A')} |
| **At Risk Level** | {snapshot.get('at_risk', 'N/A')} |
| **Data Quality** | {assessment.get('data_quality_score', 'N/A')}% |

---

## Overall Health Status

# {emoji} {assessment['overall_rag'].upper()}

**Composite Score:** {assessment['composite_score']}/3.00  
**Confidence Level:** {assessment['confidence']}

---

## Dimension Breakdown

{_format_dimension_table(assessment['dimensions'])}

---

## Analysis & Reasoning

{reasoning}

---

## Supporting Metrics

{_format_metrics_section(assessment['dimensions'])}

---

"""
    
    # Add override notes if any
    overrides = assessment.get("composite_details", {}).get("overrides_applied", [])
    if overrides:
        report += "\n## Override Notes\n\n"
        for o in overrides:
            report += f"> ⚠️ {o}\n\n"
    
    report += f"\n---\n\n*Report generated by Project Health Reporting Agent v1.0*\n"
    
    return report, assessment


def save_weekly_report(project: Dict, output_dir: Optional[Path] = None) -> Tuple[str, Dict[str, Any]]:
    """
    Generate and save a weekly report for a project.
    
    Returns a tuple containing the path to the saved report and the assessment dictionary.
    """
    if output_dir is None:
        output_dir = config.WEEKLY_DIR
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    report_content, assessment = generate_weekly_report(project)
    
    # Create filename
    project_name = assessment["project_name"].replace(" ", "_").replace("/", "-")[:50]
    run_date_str = datetime.now().strftime('%Y-%m-%d')
    filename = f"{run_date_str}_{project_name}_health_report.md"
    
    filepath = output_dir / filename
    filepath.write_text(report_content, encoding="utf-8")
    
    # Also save assessment as JSON for monthly synthesis
    json_filename = f"{run_date_str}_{project_name}_assessment.json"
    json_path = output_dir / json_filename
    
    # Make assessment JSON-serializable
    json_assessment = json.loads(json.dumps(assessment, default=str))
    json_path.write_text(json.dumps(json_assessment, indent=2, default=str), encoding="utf-8")
    
    return str(filepath), assessment


def generate_all_weekly_reports(projects: List[Dict]) -> List[Dict]:
    """
    Generate weekly reports for all projects.
    
    Returns list of assessments for use in monthly synthesis.
    """
    assessments = []
    
    for project in projects:
        if "_error" in project and "plan" not in project:
            print(f"⚠️  Skipping {project.get('filename', 'unknown')} — load error")
            continue
        
        try:
            filepath, assessment = save_weekly_report(project)
            assessments.append(assessment)
            emoji = config.RAG_EMOJIS.get(assessment["overall_rag"], "⚪")
            print(f"  {emoji} {assessment['project_name']}: {assessment['overall_rag']} "
                  f"(score: {assessment['composite_score']}) → {filepath}")
        except Exception as e:
            print(f"  ❌ Error generating report for {project.get('project_name', 'unknown')}: {e}")
            import traceback
            traceback.print_exc()
    
    return assessments


if __name__ == "__main__":
    from data_loader import load_all_projects
    
    print("📊 Generating Weekly Health Reports...")
    print(f"{'='*60}")
    
    projects = load_all_projects()
    assessments = generate_all_weekly_reports(projects)
    
    print(f"\n{'='*60}")
    print(f"✅ Generated {len(assessments)} reports in: {config.WEEKLY_DIR}")
